import type { Metadata } from "next";
import { Lexend_Deca, Aboreto } from "next/font/google";
import "./globals.css";

const lexendD = Lexend_Deca({
  variable: "--font-lexend-giga",
  subsets: ["latin"],
});

const aboreto = Aboreto({
  variable: "--font-aboreto",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "ShaadiPic",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexendD.variable} ${aboreto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
